const map = {
  map: {
    name: "stonehalls2",
    worldspawns: ["nonoclip", "nooverbounce"],
    levelshots: {
      default: "8d95768a-fa04-95e3-71aa-fed4f5bb9dc4.tga",
      cc: "c5b650ac-c16b-50ec-d7b0-520a8ca2f810.tga",
    },
    mapfeatures: ["target_starttimer"],
    arena: {
      map: "stonehalls2",
      longname: "^nStonehalls ^j2",
      type: "wolfmp wolfsw",
      timelimit: "60",
      axisRespawnTime: "1",
      alliedRespawnTime: "1",
      briefing: "^wMapped by ^3SHUT ^3UP ^3MOM ^3im ^313 ^3now",
      mapposition_x: "333",
      mapposition_y: "444",
    },
    textFiles: [],
    shaderInfo: [],
    fileTree: {
      folder_count: 23,
      file_count: 180,
      filetree: [
        {
          name: "maps",
          type: "directory",
          children: [
            { name: "stonehalls2.prt", type: "file" },
            { name: "stonehalls2.script", type: "file" },
            { name: "stonehalls2.srf", type: "file" },
            {
              name: "stonehalls2",
              type: "directory",
              children: [
                { name: "lm_0000.tga", type: "file" },
                { name: "lm_0001.tga", type: "file" },
                { name: "lm_0002.tga", type: "file" },
                { name: "lm_0003.tga", type: "file" },
                { name: "lm_0004.tga", type: "file" },
                { name: "lm_0005.tga", type: "file" },
                { name: "lm_0006.tga", type: "file" },
                { name: "lm_0007.tga", type: "file" },
                { name: "lm_0008.tga", type: "file" },
                { name: "lm_0009.tga", type: "file" },
                { name: "lm_0010.tga", type: "file" },
                { name: "lm_0011.tga", type: "file" },
                { name: "lm_0012.tga", type: "file" },
                { name: "lm_0013.tga", type: "file" },
                { name: "lm_0014.tga", type: "file" },
                { name: "lm_0015.tga", type: "file" },
                { name: "lm_0016.tga", type: "file" },
                { name: "lm_0017.tga", type: "file" },
                { name: "lm_0018.tga", type: "file" },
                { name: "lm_0019.tga", type: "file" },
                { name: "lm_0020.tga", type: "file" },
                { name: "lm_0021.tga", type: "file" },
                { name: "lm_0022.tga", type: "file" },
                { name: "lm_0023.tga", type: "file" },
                { name: "lm_0024.tga", type: "file" },
                { name: "lm_0025.tga", type: "file" },
                { name: "lm_0026.tga", type: "file" },
                { name: "lm_0027.tga", type: "file" },
                { name: "lm_0028.tga", type: "file" },
                { name: "lm_0029.tga", type: "file" },
                { name: "lm_0030.tga", type: "file" },
                { name: "lm_0031.tga", type: "file" },
                { name: "lm_0032.tga", type: "file" },
                { name: "lm_0033.tga", type: "file" },
                { name: "lm_0034.tga", type: "file" },
                { name: "lm_0035.tga", type: "file" },
                { name: "lm_0036.tga", type: "file" },
                { name: "lm_0037.tga", type: "file" },
                { name: "lm_0038.tga", type: "file" },
                { name: "lm_0039.tga", type: "file" },
                { name: "lm_0040.tga", type: "file" },
              ],
            },
            { name: "stonehalls2.bsp", type: "file" },
          ],
        },
        {
          name: "sound",
          type: "directory",
          children: [
            { name: "thomas.wav", type: "file" },
            {
              name: "scripts",
              type: "directory",
              children: [{ name: "stonehalls2.sounds", type: "file" }],
            },
            {
              name: "vo",
              type: "directory",
              children: [
                {
                  name: "stonehalls2",
                  type: "directory",
                  children: [{ name: "news_stonehalls2.wav", type: "file" }],
                },
              ],
            },
            { name: "lava.wav", type: "file" },
            { name: "portal.wav", type: "file" },
            { name: "stonedoor.wav", type: "file" },
            { name: "devilbreath.wav", type: "file" },
          ],
        },
        {
          name: "textures",
          type: "directory",
          children: [
            {
              name: "Stonehalls2",
              type: "directory",
              children: [
                { name: "banner_strgg.tga", type: "file" },
                { name: "base4_stonehalls2.tga", type: "file" },
                { name: "chain.tga", type: "file" },
                { name: "ctf_blueflag.tga", type: "file" },
                { name: "dsiglass.tga", type: "file" },
                { name: "dsitinfx.tga", type: "file" },
                { name: "flame1.tga", type: "file" },
                { name: "flame2.tga", type: "file" },
                { name: "flame3.tga", type: "file" },
                { name: "flame4.tga", type: "file" },
                { name: "flame5.tga", type: "file" },
                { name: "flame6.tga", type: "file" },
                { name: "flame7.tga", type: "file" },
                { name: "flame8.tga", type: "file" },
                { name: "flameball.tga", type: "file" },
                { name: "fog_stonehalls2.tga", type: "file" },
                { name: "ice_sfx.jpg", type: "file" },
                { name: "ice_slick2_blue.tga", type: "file" },
                { name: "ice_slick2_green.tga", type: "file" },
                {
                  name: "kokopaskakaartaaloivastioikeelle.jpg",
                  type: "file",
                },
                { name: "poem.tga", type: "file" },
                { name: "poemonwood.tga", type: "file" },
                { name: "portaali.tga", type: "file" },
                { name: "portaali2.tga", type: "file" },
                { name: "protobanner.tga", type: "file" },
                { name: "protobanner_ow.tga", type: "file" },
                { name: "protolava.tga", type: "file" },
                { name: "protolava2.tga", type: "file" },
                { name: "wood5.jpg", type: "file" },
                { name: "wood5b.jpg", type: "file" },
                { name: "woodtrim1.tga", type: "file" },
                { name: "woodtrim2-1-1.tga", type: "file" },
                { name: "woodtrim2-1.tga", type: "file" },
              ],
            },
            {
              name: "sac",
              type: "directory",
              children: [
                { name: "banner_strgg.tga", type: "file" },
                { name: "bild1.jpg", type: "file" },
                { name: "bild2.jpg", type: "file" },
                { name: "bild3.jpg", type: "file" },
                { name: "bild4.jpg", type: "file" },
                { name: "bild5.jpg", type: "file" },
                { name: "bild6.jpg", type: "file" },
                { name: "brickred_01.jpg", type: "file" },
                { name: "clanlogo.jpg", type: "file" },
                { name: "credits.jpg", type: "file" },
                { name: "firegorre2.jpg", type: "file" },
                { name: "firewalla.tga", type: "file" },
                { name: "fridge.jpg", type: "file" },
                { name: "killsky_1.jpg", type: "file" },
                { name: "killsky_2.jpg", type: "file" },
                { name: "noobpad.jpg", type: "file" },
                { name: "protobanner.tga", type: "file" },
                { name: "protobanner_ow.tga", type: "file" },
                { name: "refrigerator.jpg", type: "file" },
                { name: "screen.jpg", type: "file" },
                { name: "stage1.tga", type: "file" },
                { name: "stage2.tga", type: "file" },
                { name: "stage3.tga", type: "file" },
                { name: "Thumbs.db", type: "file" },
                { name: "tinfx2.jpg", type: "file" },
              ],
            },
            {
              name: "Stonehalls2_decals",
              type: "directory",
              children: [
                { name: "airstrafes.tga", type: "file" },
                { name: "crimes.tga", type: "file" },
                { name: "curvznshiet.tga", type: "file" },
                { name: "lightshouldbebanned.tga", type: "file" },
                { name: "muzzleonface.tga", type: "file" },
                { name: "poem.tga", type: "file" },
                { name: "possessed.tga", type: "file" },
                { name: "seriousstuff.tga", type: "file" },
                { name: "straightgammas.tga", type: "file" },
                { name: "walkingmemegenerator.tga", type: "file" },
              ],
            },
            {
              name: "celshader",
              type: "directory",
              children: [
                { name: "black.tga", type: "file" },
                { name: "c1.tga", type: "file" },
                { name: "c2.tga", type: "file" },
                { name: "c3.tga", type: "file" },
                { name: "c4.tga", type: "file" },
                { name: "c5.tga", type: "file" },
                { name: "c6.tga", type: "file" },
                { name: "c7.tga", type: "file" },
                { name: "c8.tga", type: "file" },
                { name: "c9.tga", type: "file" },
              ],
            },
          ],
        },
        {
          name: "scripts",
          type: "directory",
          children: [
            { name: "stonehalls2.arena", type: "file" },
            { name: "stonehalls2_cc.shader", type: "file" },
            { name: "stonehalls2.shader", type: "file" },
            { name: "stonehalls2_2.shader", type: "file" },
            { name: "sac.shader", type: "file" },
            { name: "water.shader", type: "file" },
            { name: "sh2_decals.shader", type: "file" },
            { name: "999n5.shader", type: "file" },
          ],
        },
        {
          name: "levelshots",
          type: "directory",
          children: [
            { name: "stonehalls2_cc.tga", type: "file" },
            { name: "stonehalls2.tga", type: "file" },
          ],
        },
        {
          name: "video",
          type: "directory",
          children: [{ name: "flame.roq", type: "file" }],
        },
        {
          name: "models",
          type: "directory",
          children: [
            {
              name: "mapobjects",
              type: "directory",
              children: [
                {
                  name: "Xaero_statue",
                  type: "directory",
                  children: [
                    { name: "xaero_statue.MD3", type: "file" },
                    { name: "xaero_statue.tga", type: "file" },
                    { name: "xaero_statue_a.tga", type: "file" },
                    { name: "xaero_statue_h.tga", type: "file" },
                    { name: "xaero_statue_q.tga", type: "file" },
                  ],
                },
                {
                  name: "Dm_statue",
                  type: "directory",
                  children: [
                    { name: "dm_statue.MD3", type: "file" },
                    { name: "dm_statue.tga", type: "file" },
                    { name: "dm_statue_a.tga", type: "file" },
                    { name: "dm_statue_h.tga", type: "file" },
                    { name: "dm_statue_q.tga", type: "file" },
                  ],
                },
                {
                  name: "horned",
                  type: "directory",
                  children: [
                    { name: "horned.md3", type: "file" },
                    { name: "horned.tga", type: "file" },
                  ],
                },
                {
                  name: "jesus",
                  type: "directory",
                  children: [{ name: "jesuswall.tga", type: "file" }],
                },
                {
                  name: "q",
                  type: "directory",
                  children: [
                    { name: "eagleban.md3", type: "file" },
                    { name: "jesus.md3", type: "file" },
                    { name: "monkeyface.md3", type: "file" },
                    { name: "skull.md3", type: "file" },
                    { name: "skull_tilt1.md3", type: "file" },
                    { name: "standinglamp1.md3", type: "file" },
                    { name: "timdm5_ceiling2.md3", type: "file" },
                    { name: "timdm5_wall1.md3", type: "file" },
                  ],
                },
                {
                  name: "baph",
                  type: "directory",
                  children: [
                    { name: "bapholamp.md3", type: "file" },
                    { name: "bapholamp2b.md3", type: "file" },
                    { name: "bapholamp2r.md3", type: "file" },
                    { name: "bapholamp_fx.jpg", type: "file" },
                    { name: "bapholamp_fx2.jpg", type: "file" },
                    { name: "baphomet.tga", type: "file" },
                    { name: "baphomet_gold.md3", type: "file" },
                    { name: "baphomet_gold.tga", type: "file" },
                    { name: "bapho_lamp.jpg", type: "file" },
                    { name: "lil_baphomet.md3", type: "file" },
                    { name: "wrist.jpg", type: "file" },
                  ],
                },
                {
                  name: "pentagrams",
                  type: "directory",
                  children: [
                    { name: "penta_bone.jpg", type: "file" },
                    { name: "penta_flr_bone.MD3", type: "file" },
                    { name: "penta_flr_stone.MD3", type: "file" },
                    { name: "penta_stone.jpg", type: "file" },
                    { name: "penta_wall_bone.MD3", type: "file" },
                    { name: "penta_wall_stone.MD3", type: "file" },
                    { name: "Thumbs.db", type: "file" },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    release: "12/06/2021",
  },
};
